### ISSUE TITLE
请问build之后如何启用此插件

### ISSUE THREAD

**Issue by ycgambo** [luxingwen/emqx-persistence-plugin#10]
按照readme执行，build之后通过console启动，emqx_ctl plugins list 和models list 列表里面并没有出现。

存在这个目录：`_build/emqx/lib/emqx_persistence_plugin`

请问如何启动呢？

**Comment by dingiso** [comment]
我也是这个问题，我直接尝试了添加 $PERSISTENCE 没有生效，请问你是怎么解决的
