### ISSUE TITLE
$P2P/clientid的定点发送在集群环境下无效

### ISSUE THREAD

**Issue by wwlwxg** [luxingwen/emqx-persistence-plugin#7]
测试步骤：
1. 建立集群两台机器，192.168.30.31，192.168.30.32
2. 客户端1连接192.168.30.31，clientid 为 888888，客户端2连接192.168.30.31，发送主题为$P2P/888888的消息，客户端1可以收到消息，ok
3. 客户端1连接192.168.30.31，clientid为 888888，客户端2连接192.168.30.32，发送主题为$P2P/888888的消息，客户端1收不到消息，no ok

原因分析：
发送主题$P2P/888888在集群中没有这个topic，所以服务器没有做转发，所以在集群中跨越机器无效

操作：插件中将此topic发送到其他集群所有机器

**Comment by wwhai** [comment]
> 测试步骤：
> 
> 1. 建立集群两台机器，192.168.30.31，192.168.30.32
> 2. 客户端1连接192.168.30.31，clientid 为 888888，客户端2连接192.168.30.31，发送主题为$P2P/888888的消息，客户端1可以收到消息，ok
> 3. 客户端1连接192.168.30.31，clientid为 888888，客户端2连接192.168.30.32，发送主题为$P2P/888888的消息，客户端1收不到消息，no ok
> 
> 原因分析：
> 发送主题$P2P/888888在集群中没有这个topic，所以服务器没有做转发，所以在集群中跨越机器无效
> 
> 操作：插件中将此topic发送到其他集群所有机器

已经修复了
